backend:
  name: github
  repo: jaweed3/ksatria2028
  branch: main
  auth_type: pkce
  app_id: Ov23liiiYlS8fu7gZrx6

publish_mode: editorial_workflow
media_folder: public/uploads
public_folder: /uploads

collections:
  - name: blog
    label: Blog
    folder: src/content/posts
    create: true
    slug: "{{slug}}"
    preview_path: blog/{{slug}}
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Date, name: date, widget: datetime, default: "" }
      - { label: Image, name: image, widget: image, required: false }
      - { label: Body, name: body, widget: markdown }
